# Generated by Django 3.0.4 on 2020-03-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='Title', max_length=128)),
                ('cover_type', models.CharField(choices=[('Softcover', 'Soft'), ('Hardcover', 'Hard')], db_column='CoverType', default='Softcover', max_length=64)),
                ('creation_at', models.DateTimeField(auto_now_add=True, db_column='CreationDate')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='')),
            ],
            options={
                'db_table': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_column='URL', max_length=256)),
                ('caption', models.CharField(db_column='Caption', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Album')),
            ],
            options={
                'db_table': 'Photo',
            },
        ),
    ]
