# Generated by Django 3.0.4 on 2020-03-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Created'),
        ),
        migrations.AlterField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='LastUpdated'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='Created'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='LastUpdated'),
        ),
    ]
