# Generated by Django 3.0.4 on 2020-03-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200309_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=0, upload_to='PHOTOS/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
